#!/bin/bash
#
###########################################################################
#
# Nome       : backup_geral.conf
# Descricao  : Configuracoes para o backup_sistemas.sh funcionar
# Author     : Jose Edson Moreno Jr.
# Email      : edson.moreno@gmail.com
# Versao     : 0.3
# Data       : 10/01/2018
# copyright  : (C) 2018 by Edson Moreno
# Parametros :
# Retorno    :
#
# CHANGELOG  :
############################################################################


# Servidores que serao efetuados o backup, cada servidor separado por espaco.
# Se a porta de conexao SSH for diferente da padrao, especificar servidor:porta.
Servers="srv-web-01 srv-db-01 srv-app-01 srv-files-01 srv-monitoring-01 srv-legacy-01:2222"

Dir_Temp="/var/tmp"
Dir_Backup="/backup"
Backups_Simultaneos=4
Retensao=7

# Espaco minimo livre em % para ocorrer o backup.
limite_espaco=4

# Parametros de envio de email.
Email="admin@example.net"
EMAIL_FROM="backup@example.net"
EMAIL_FROM_DESC="Backup Linux"
EMAIL_SUBJ="[${EMAIL_FROM_DESC}] - Relatorio Backup"
EMAIL_SERVER="mail.example.net"
EMAIL_PORT="25"

# Localizacao netcat.
NC="/usr/bin/nc"
